# -*- coding: utf-8 -*-
"""ML01_LogisticRegression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XpYSLINif2bX-EBSWQRaLqNi7Chp7uAo
"""



import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

url = "https://raw.githubusercontent.com/hyeonx3/ML_Project/main/dataset/spotify_songs_with_genre_int.csv"
df = pd.read_csv(url)

target_col = "genre_int"
features = ["track_popularity","danceability","energy","key","loudness","mode", "speechiness","acousticness","instrumentalness","liveness","valence", "tempo","duration_ms"]

numeric_cols = df[features].select_dtypes(include=["int64", "float64"]).columns.tolist()

X = df[numeric_cols]
y = df[target_col]

# 3. train / temp (70 / 30)
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y,
    test_size=0.30,
    stratify=y,
    random_state=42
)

# 4. temp → val / test (15 / 15)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp,
    test_size=0.50,
    stratify=y_temp,
    random_state=42
)

print("train:", X_train.shape)
print("val  :", X_val.shape)
print("test :", X_test.shape)

c_candidates = [0.01, 0.1, 1, 10, 100]
best_c = None
best_val_acc = -1

for c in c_candidates:
    model = Pipeline([
        ("scaler", StandardScaler()),
        ("clf", LogisticRegression(
            C=c,
            multi_class="multinomial",
            solver="lbfgs",
            max_iter=1000
        ))
    ])
    model.fit(X_train, y_train)
    val_acc = model.score(X_val, y_val)
    print(f"C={c} → val acc={val_acc:.4f}")

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        best_c = c

print(f"\n[선택] val 기준으로 가장 좋은 C는 {best_c} (acc={best_val_acc:.4f})")

# ------------------------------------------------
# 4. 가장 좋은 C로 다시 모델 만들어서
#    train 전체에 fit → test에서 평가
#    (val을 합쳐서 다시 학습해도 되지만 지금은 간단 버전)
# ------------------------------------------------
final_model = Pipeline([
    ("scaler", StandardScaler()),
    ("clf", LogisticRegression(
        C=best_c,
        multi_class="multinomial",
        solver="lbfgs",
        max_iter=1000
    ))
])

final_model.fit(X_train, y_train)

# 5. 테스트셋 예측
y_pred = final_model.predict(X_test)

# 6. 혼동 행렬 만들기
cm = confusion_matrix(y_test, y_pred)
labels = np.unique(y)   # 장르 인덱스들

print("\n=== Confusion matrix (raw) ===")
print(cm)

# 7. 좀 더 친절하게: 행=실제, 열=예측 이라고 써주고
print("\n행 = 실제 장르, 열 = 예측 장르")
print("labels:", labels)

# 8. 판다스로 보기 좋게
cm_df = pd.DataFrame(cm, index=[f"true_{l}" for l in labels],
                        columns=[f"pred_{l}" for l in labels])
print("\n=== Confusion matrix (table) ===")
print(cm_df)